### PR TITLE
Update actions' checkout, upload-artifact, download-artifact to v3

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update github actions checkout and upload/download artifact from v1/v2 to v3 to solve deprecated warnings.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | workflows' build-release complete without warnings of deprecated github actions or command.

### CODE REVIEW

**Comment by kpodemski** [comment]
Hmm, I think we should use the same strategy as here:
https://github.com/PrestaShop/ps_categorytree/blob/dev/.github/workflows/build-release.yml

This way we change the build-release workflow from one place.

**Comment by leemyongpakvn** [comment]
@kpodemski  I have done similar thing at https://github.com/PrestaShop/blockreassurance/pull/521 , as recommended by @SharakPL , but Build-Release Deprecated warning is still there because _Organization Build Release Github Action_ is deprecated now. It looks like @atomix does not have time to continue his plan recently :)

**Comment by kpodemski** [comment]
@SharakPL could you elaborate? what do you think it is deprecated way of releasing modules?

**Comment by kpodemski** [comment]
Hi @leemyongpakvn 

I checked with @SharakPL and can confirm that there was some misunderstanding.

He [mentioned](https://github.com/PrestaShop/blockreassurance/pull/516#issuecomment-1476484772) that the plan is to keep using organizational build-release.yml.

You were worried because of NeoMaking message about `prestashop-eslint-config`, but those two are totally different. Eslint config is a pain because there are better alternatives, on the other hand, having a dedicated build-release.yml in every single module is a pain because [we can have one point where the build is being done](https://github.com/PrestaShop/.github/blob/master/.github/workflows/build-release.yml), and we're good. We don't plan to abandon or deprecate this.

**Comment by kpodemski** [comment]
We could update the organizational build release if needed.

**Comment by leemyongpakvn** [comment]
@kpodemski There is really no misunderstanding between `prestashop-eslint-config` and `organizational build-release.yml` here :), my concern is about `organizational build-release.yml` only, as we can see at the most recent merged PS https://github.com/PrestaShop/blockreassurance/actions/runs/5094791527, the deprecated warnings are still there after switch to use `organizational build-release.yml`.

**Comment by kpodemski** [comment]
@leemyongpakvn you're right, we need to update build-release.yml from .github repo, for example, I see that the action we use from PrestaShopCorp is v1 while their released v2, etc.

**Comment by leemyongpakvn** [comment]
Waiting for common Build-Release update.

**Comment by kpodemski** [comment]
@leemyongpakvn merged, let's see actions now

**Comment by leemyongpakvn** [comment]
@kpodemski  Organization Build & Release looks well this time.

**Review by kpodemski — APPROVED** [review]

**Pull request merged**
